include kitty_gruvbox_theme/gruvbox_dark.conf

set preview_images true
set preview_images_method ueberzug

background_opacity 0.85

window_padding_width 10

# Disable the window title bars
hide_window_decorations yes

# You can further customize your kitty with additional settings such as:
# Font family and size
font_family      CaskaydiaCove Nerd Font
font_size        15.0

# Enable ligatures in code
disable_ligatures never

# Set the initial window size (columns and rows)
remember_window_size no
initial_window_width  850
initial_window_height 600

map super+shift+enter new_os_window_with_cwd
