{...}: {
  imports = [
    ./web-devicons.nix
    ./vimtex.nix
    ./toggleterm.nix
    ./autopairs.nix
    ./lualine.nix
    ./lsp.nix
    ./cmp.nix
    ./treesitter.nix
    ./fzf.nix
    ./oil.nix
    ./diffview.nix
    ./surround.nix
    ./luasnip.nix
    ./neogit.nix
    ./flash.nix
    ./indent-blankline.nix
    ./ts-autotag.nix
    ./css-color.nix
    ./yazi-nvim.nix
    ./molten.nix
    ./markdown.nix
    ./lint.nix
    ./bufferline.nix
    ./mini.nix
    ./illuminate.nix
  ];
}
